### ISSUE TITLE
Second y plotted series lines seems have an offset

### ISSUE THREAD

**Issue by konato** [data-forge/data-forge-plot#12]
Hi, 

I'm plotting two series using the following plot command in DFN Pro 1.10.3: 

display.plot(t, { }, { x: "date", y: "new_confirmed", y2: "avg_new_confirmed_7days" });

The avg_new_confirmed_7days lines has an offset as you can see on joined screen capture. 
On December 12 data point, the avg value is :  1508.71... but shows in the 2500-3000 range on the plot.

<img width="981" alt="Capture d’écran, le 2021-02-02 à 14 20 57" src="https://user-images.githubusercontent.com/73777/106654043-97558a80-6565-11eb-8aa2-1315e916e753.png">

Is this a problem or did I just forgot to pass some parameters?

A second question, is it possible to mix a line and a bar chart. I went to C3 they have this kind of graph, did try to do the same in DFN. It doesn't seems to work. 

Here is my plot command : display.plot(t, { type: 'bar', types: { avg_new_confirmed_7days: 'line'} }, { x: "date", y: "new_confirmed", y2: "avg_new_confirmed_7days" });

Thank you, 

Stéphane

**Comment by ashleydavis** [comment]
Hi @konato, can you please submit an example notebook that shows the problem?

It can't do mixed charts yet. But I'll look into that soon.

**Comment by ashleydavis** [comment]
You can synchronize the y axis' by setting min/max values for each, like this:

![image](https://user-images.githubusercontent.com/625126/106872382-57d69c00-6727-11eb-8c79-7214ee3f1a6f.png)

I'm working on mixed charts. But it will be a couple of weeks before I do a new build.

**Comment by konato** [comment]
It does work fine. 
It will be great to have mixed charts in the future. 

Thank you very much for your help.

**Comment by ashleydavis** [comment]
I've implemented mixed charts (published yesterday) in the Plot library (https://www.npmjs.com/package/plot).

This will be included in the next release of DFN (v1.10.4) which I'll aim to publish in the next couple of weeks.

By the way, I'm also working to improve the documentation for the Plot function, you can check it out here:
https://data-forge-notebook.github.io/plot/

Let me know if you have any feedback about the docs!

**Comment by ashleydavis** [comment]
@konato just letting you know that I've implemented the mixed charts in DFN.

Version 1.10.4 will be release in the next couple of weeks.

When you get it make sure you look at the charts example notebook to see how it works.

**Comment by konato** [comment]
I'll do and will try a mixed chart. Thank you.
