### ISSUE TITLE
Error installing data-forge-render

### ISSUE THREAD

**Issue by barryshultz** [data-forge/data-forge-plot#3]
When I try to install data-forge-render, the installation fails with the following errors:

npm install --save data-forge-render
npm ERR! code E404
npm ERR! 404 Not Found: data-forge-render@latest

**Comment by ashleydavis** [comment]
Thanks so much for your feedback.

The name of the module is `@data-forge-plot/render`.

You need to install it like this:

```
npm install --save @data-forge-plot/render
```

Sorry the docs are wrong! I'll update then.
