### ISSUE TITLE
Specifying x-axis timeseries label format

### ISSUE THREAD

**Issue by barryshultz** [data-forge/data-forge-plot#4]
I am charting a dataframe whose time series ranges over several days, with millisecond granularity. The x-axis label is defaulting to 'HH:mm'. Is there a way to specify x-axis labels with other formats (e.g., 'DD.MM HH:mm')? Thanks in advance.

**Comment by ashleydavis** [comment]
Hi, thanks for you feedback.

I'm not sure if that's possible yet, but if not I can add it for you very quickly.

Are you able to provide me some example code that I can use to test it?  Just a small example will do. You can attach a source file or a zip file to this issue, or you can give me a link to a GitHub repo or a gist.

Thanks for your help.

**Comment by barryshultz** [comment]
[test-data-forge.zip](https://github.com/data-forge/data-forge-plot/files/3221955/test-data-forge.zip)

I've uploaded a sample CSV file and the short test program I run against it. Thanks for having a look at it.

**Comment by ashleydavis** [comment]
Just had a look, what you want is already possible, you can set the x axis format as follows:

`await plRcv.plot({ x: { format: "DD.MM.HH:mm" }}).renderImage("packetlossreport-02.png");
`
Sorry for the poor documentation! 

This project is progressing slowly towards being complete :)
