### ISSUE TITLE
Configuring the font size on x- and y-axis

### ISSUE THREAD

**Issue by barryshultz** [data-forge/data-forge-plot#5]
Is it possible to change the font size on one or both axes? I have not been able to discover how, if it is possible. Thanks.

**Comment by ashleydavis** [comment]
I've been looking through the ApexCharts docs to see if there's any option for it: https://apexcharts.com/docs

I haven't found anything yet.

I've left a request on AxisCharts to see if this is possible: https://github.com/apexcharts/apexcharts.js/issues/684

**Comment by ashleydavis** [comment]
Ok, it's possible to do this with ApexCharts, but I'll need to wire it up for you. Get back to you soon.

**Comment by barryshultz** [comment]
Thanks for looking into that

**Comment by ashleydavis** [comment]
You can now configure font size and family on x axis, y axis and the legend.

Be sure to use [Data-Forge Plot v0.6.0](https://www.npmjs.com/package/data-forge-plot).

Please see [example 12](https://github.com/data-forge/data-forge-plot-examples/blob/master/typescript/example-12.ts) to see how to use it.

**Comment by ashleydavis** [comment]
If features are missing please keep asking for them! That's what drives this forward.

**Comment by barryshultz** [comment]
Hi, Thanks very much for the help. I looked at example 12 and I think there's a small understanding. Using the example to guide me, I can change the x-axis label font, but I am actually interested in the font of the labels at the tick marks. For example, in this [example](https://apexcharts.com/javascript-chart-demos/line-charts/basic/) I would want to control the font size of the month names (Jan, Feb, etc.). Is that also possible already in v0.6.0?

**Comment by ashleydavis** [comment]
Ok I see! I should have covered that case as well. Give me a day or two to look into it!

**Comment by ashleydavis** [comment]
Check out Data-Forge Plot version 0.6.2.

I've updated [example 12](https://github.com/data-forge/data-forge-plot-examples/blob/master/typescript/example-12.ts) to show how to configure the font for tick marks.

Please let me know if this does what you need.

**Comment by barryshultz** [comment]
Yes, it's working exactly the way I wanted. Thanks :-).

**Comment by ashleydavis** [comment]
That's great.

Please be sure to star my repos if you haven't already:

https://github.com/data-forge/data-forge-ts
https://github.com/data-forge/data-forge-plot

Thanks!
