### ISSUE TITLE
X axis min / max or Scale setting ?

### ISSUE THREAD

**Issue by dharders** [data-forge/data-forge-plot#7]
Hey, is there a way to set the X axis min / max or have it auto scale? (Awesome library btw!)

I'm plotting motion data versus time with an input CSV file in the form of:
```
time, accel, velocity, displacement
0, 0, 0, 0
0.01, 0.2, 0.02, 0.002
... etc
```

I'm processing the data with the following code:
```typescript
let df = dataForge.fromCSV(this.csvData, { dynamicTyping: true }).dropSeries("time");
let plot = df.plot( { width: 2000, height: 1000  });
fse.emptyDirSync(this.outputPath);
await plot.exportWeb(path.join(this.outputPath, "web"), { overwrite: true, openBrowser: true });
```

The above code plots all Y values (accel, velocity, displacement) correctly. The X values (time) are **wrong** though and just incrementing sample integers, as expected, as we dropped the time series.

However, if I set the dataFrame index to "time" I'd expect the X values to now be the given time values . 

i.e.
```typescript
let df = dataForge.fromCSV(this.csvData, { dynamicTyping: true }).setIndex("time").dropSeries("time");
```

The plot that is generated keeps the same **wrong** axis labels (incrementing integers from 1 to the total number of sample points) but plots all my Y values seemingly on the first tick of the chart.

I believe this is a X axis scaling issue, as all of my time values are below 1.0, and if I look at the `chart-def.json` file the index values are indeed my time values. It's just in the display that is broken. 

If I multiply all of my index values by 100, it produces a better chart (because we have X values greater than 1), but the X axis labels and scaling are still set as though I didn't change my Index.

i.e. If I could set the X axis to only display between 0.0 and 1.0 I'd believe I could see the entire chart.

Any Ideas?

Thanks again for creating this awesome tool!

P.S. To get the `exportWeb()` function to work correctly I had to firstly modify the generated `index.js` file and change all references of `inputChartDef` in the `function formatChartDef(inputChartDef){ }` to `inputChartDef.chartDef` before my chart would open in the browser correctly (MS Edge)
This may or may not be related...

**Comment by ashleydavis** [comment]
Hi Dale, thanks for your feedback. I'm taking a break for Christmas and the new year at the moment. You might have to remind me to look at this in a few weeks time.

I don't think there is anyway yet to do it yet. Sorry for the inconvenience.

I'm actually currently working on a new plotting library that is similar to data-forge-plot but independent of data-forge: https://www.npmjs.com/package/plot

Plot is like an improved version of data-forge-plot, but simply works with JavaScript data and you don't have to load a dataframe to use it.

In the next couple of months plot will supersede data-forge-plot and I'll re-engineer data-forge-plot to be a wrapper around plot.

Unfortunately I have so many commitments at the moment that I'm finding it difficult to get time to work on open source code. I can only fit an hour or two a week! So it's moving more slowly than I had hoped. 

If you were interested you are welcome to contribute and help me move it forward!

Cheers
Ashley Davis

**Comment by dharders** [comment]
Thanks for your reply Ashley! I'll take a look at your other library and see if it does the job. Enjoy your break!
